//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Receipt_Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRM_Receipt_Delivery()
        {
            this.CRM_Receipt_Details = new HashSet<CRM_Receipt_Details>();
        }
    
        public long ReceiptID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string OrderName { get; set; }
        public string OrderAddress { get; set; }
        public string OrderPhone { get; set; }
        public string ReceiveName { get; set; }
        public string ReceiveAddress { get; set; }
        public string ReceivePhone { get; set; }
        public Nullable<double> Shipping { get; set; }
        public Nullable<double> TotalReduceAmount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> TotalPaid { get; set; }
        public Nullable<double> TotalRemain { get; set; }
        public bool IsOrdered { get; set; }
        public bool IsPaid { get; set; }
        public bool IsDeliveried { get; set; }
        public bool IsReceived { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FormPayment { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual CRM_Customer CRM_Customer { get; set; }
        public virtual CRM_Employee CRM_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRM_Receipt_Details> CRM_Receipt_Details { get; set; }
    }
}
