//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Receipt_Details
    {
        public long ReceiptDetailsID { get; set; }
        public Nullable<long> ReceiptDeliveryID { get; set; }
        public Nullable<long> ReceiptReturnID { get; set; }
        public Nullable<long> ReceiptWarehouseID { get; set; }
        public long ProductID { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; }
        public double ReducePrice { get; set; }
    
        public virtual CRM_Product CRM_Product { get; set; }
        public virtual CRM_Receipt_Delivery CRM_Receipt_Delivery { get; set; }
        public virtual CRM_Receipt_Return CRM_Receipt_Return { get; set; }
        public virtual CRM_Receipt_Warehouse CRM_Receipt_Warehouse { get; set; }
    }
}
