//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_User
    {
        public string UserID { get; set; }
        public string FullName { get; set; }
        public string Roles { get; set; }
    }
}
